#!/usr/bin/env python3
import os
import struct
import sys

SECTORS = 2880
SECTOR_SZ = 512
SPT = 18
HEADS = 2
CYLS = 80

FAT_COUNT = 2
FAT_SECS = 9
ROOT_ENTRIES = 224
ROOT_SECS = ROOT_ENTRIES * 32 // SECTOR_SZ
SECS_CLUS = 1

RESERVED_SECS = 5
FAT1_LBA = RESERVED_SECS
FAT2_LBA = FAT1_LBA + FAT_SECS
ROOT_LBA = FAT2_LBA + FAT_SECS
DATA_LBA = ROOT_LBA + ROOT_SECS

BOOTMETA = "coil/bootmeta.inc"

def ceil_div(a, b):
    return (a + b - 1) // b

def kernel_layout(kern):
    kern_secs = ceil_div(len(kern), SECTOR_SZ)
    kern_clus = ceil_div(len(kern), SECTOR_SZ * SECS_CLUS)
    kern_lba = DATA_LBA
    return kern_lba, kern_secs, kern_clus

def sum16(data):
    if len(data) % 2:
        data += b"\0"
    return sum(struct.unpack("<%dH" % (len(data) // 2), data)) & 0xFFFF

def emit_bootmeta(kern, quiet=False):
    kern_lba, kern_secs, _ = kernel_layout(kern)
    padded = kern + b"\0" * (kern_secs * SECTOR_SZ - len(kern))
    txt = (
        "; generated by mkfat.py\n"
        f"KERNEL_LBA equ {kern_lba}\n"
        f"KERNEL_SECS equ {kern_secs}\n"
        f"KERNEL_SEC0_SUM equ {sum16(padded[:SECTOR_SZ])}\n"
        f"KERNEL_SUM equ {sum16(padded)}\n"
    )
    os.makedirs("coil", exist_ok=True)
    old = None
    if os.path.exists(BOOTMETA):
        with open(BOOTMETA, "r", encoding="ascii") as f:
            old = f.read()
    if old != txt:
        with open(BOOTMETA, "w", encoding="ascii") as f:
            f.write(txt)
        if not quiet:
            print(f"Wrote {BOOTMETA} (lba={kern_lba}, secs={kern_secs})")

def write_sector(img, lba, data):
    if len(data) > SECTOR_SZ:
        raise SystemExit(f"sector write too large at LBA {lba}")
    off = lba * SECTOR_SZ
    img[off:off + len(data)] = data

def write_sectors(img, lba, data):
    for i in range(0, len(data), SECTOR_SZ):
        write_sector(img, lba + i // SECTOR_SZ, data[i:i + SECTOR_SZ])

def fat12_set(fat, clus, val):
    off = clus + clus // 2
    if clus & 1:
        fat[off] = (fat[off] & 0x0F) | ((val << 4) & 0xF0)
        fat[off + 1] = (val >> 4) & 0xFF
    else:
        fat[off] = val & 0xFF
        fat[off + 1] = (fat[off + 1] & 0xF0) | ((val >> 8) & 0x0F)

def build_image():
    with open("coil/stage1.bin", "rb") as f:
        s1 = bytearray(f.read())
    with open("coil/stage2.bin", "rb") as f:
        s2 = f.read()
    with open("helix.bin", "rb") as f:
        kern = f.read()

    if len(s1) != SECTOR_SZ:
        raise SystemExit("coil/stage1.bin must be exactly 512 bytes")
    if len(s2) > 4 * SECTOR_SZ:
        raise SystemExit("coil/stage2.bin must fit in 4 sectors")
    if not kern:
        raise SystemExit("helix.bin is empty")

    emit_bootmeta(kern, quiet=True)

    kern_lba, kern_secs, kern_clus = kernel_layout(kern)
    if kern_lba + kern_secs > SECTORS:
        raise SystemExit("helix does not fit in image")

    img = bytearray(SECTORS * SECTOR_SZ)

    s1[3:11] = b"BOREALIS"
    bpb = struct.pack(
        "<HBHBHHBHHHII",
        SECTOR_SZ, SECS_CLUS, RESERVED_SECS, FAT_COUNT,
        ROOT_ENTRIES, SECTORS, 0xF0, FAT_SECS, SPT, HEADS, 0, 0,
    )
    s1[11:11 + len(bpb)] = bpb
    write_sector(img, 0, s1)
    write_sectors(img, 1, s2)

    fat = bytearray(FAT_SECS * SECTOR_SZ)
    fat[0:3] = b"\xF0\xFF\xFF"
    for c in range(2, 2 + kern_clus - 1):
        fat12_set(fat, c, c + 1)
    fat12_set(fat, 2 + kern_clus - 1, 0xFF8)
    write_sectors(img, FAT1_LBA, fat)
    write_sectors(img, FAT2_LBA, fat)

    root = bytearray(ROOT_SECS * SECTOR_SZ)
    dirent = bytearray(32)
    dirent[0:11] = b"HELIX   BIN"
    dirent[11] = 0x20
    dirent[26:28] = struct.pack("<H", 2)
    dirent[28:32] = struct.pack("<I", len(kern))
    root[0:32] = dirent
    write_sectors(img, ROOT_LBA, root)

    write_sectors(img, DATA_LBA, kern)

    with open("borealis.img", "wb") as f:
        f.write(img)
    print(
        f"Built borealis.img {len(img)//1024} KB, kernel={len(kern)} bytes, "
        f"secs={kern_secs}, lba={kern_lba}"
    )

def main():
    if len(sys.argv) > 2:
        raise SystemExit("usage: mkfat.py [--bootmeta]")

    with open("helix.bin", "rb") as f:
        kern = f.read()

    if len(sys.argv) == 2:
        if sys.argv[1] != "--bootmeta":
            raise SystemExit("usage: mkfat.py [--bootmeta]")
        emit_bootmeta(kern)
        return

    build_image()

if __name__ == "__main__":
    main()
